version: 0.2

phases:
  pre_build:
    commands:
      - pip install awscli
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email  --region $AWS_DEFAULT_REGION)
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
      #- IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - echo "$IMAGE_URI"
      - DOCKER_LOGIN=`aws ecr get-login --region $AWS_DEFAULT_REGION`
      - PASSWORD=`echo $DOCKER_LOGIN | cut -d' ' -f6`
      - sed -i "s|TASK_EXECUTION_ROLE|$TASK_EXECUTION_ROLE|g" taskdef.json
      - sed -i "s|AWS_REGION|$AWS_DEFAULT_REGION|g" taskdef.json
      - sed -i "s|GHOST_DATABASE_PASSWORD|$GHOST_DATABASE_PASSWORD|g" taskdef.json
      - sed -i "s|GHOST_DATABASE_HOST|$GHOST_DATABASE_HOST|g" taskdef.json
      - sed -i "s|GHOST_ASSET_S3_BUCKET|$GHOST_ASSET_S3_BUCKET|g" taskdef.json
      - sed -i "s|GHOST_DATABASE_USER|$GHOST_DATABASE_USER|g" taskdef.json
      - sed -i "s|GHOST_URL|$GHOST_URL|g" taskdef.json
      - sed -i "s|GHOST_DATABASE_NAME|$GHOST_DATABASE_NAME|g" taskdef.json
      - sed -i "s|AWS_ACCESS_KEY_ID|$GHOST_AWS_ACCESS_KEY_ID|g" taskdef.json
      - sed -i "s|AWS_SECRET_ACCESS_KEY_ID|$GHOST_AWS_SECRET_ACCESS_KEY_ID|g" taskdef.json
      - sed -i "s|GHOST_FAMILY|$GHOST_FAMILY|g" taskdef.json
      - sed -i "s|ENV|$ENV|g" taskdef.json
      - sed -i "s|CONTAINER_NAME|$GHOST_CONTAINER_NAME|g" taskdef.json
      - sed -i "s|TASK_DEFINITION_REVISION|$TASK_DEFINITION_REVISION|g" taskdef.json
      - sed -i "s|TASK_DEFINITION_ARN|$TASK_DEFINITION_ARN|g" taskdef.json
      - sed -i "s|CONTAINER_NAME|$GHOST_CONTAINER_NAME|g" appspec.yaml
      - sed -i "s|GHOST_URL|$GHOST_URL|g" config.production.json
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - printf '{"ImageURI":"%s"}' $IMAGE_URI > imageDetail.json
artifacts:
  files:
  - imageDetail.json
  - appspec.yaml
  - taskdef.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
